#ifndef GITEN_SCRIPT_SCRIPTOPERAND_H
#define GITEN_SCRIPT_SCRIPTOPERAND_H

#include <rva.h>

#include <Enums.h>
#include <Ints.h>

// The macca / magnetite the last OpRollActorMacca / OpRollActorMagnetite
// rolled for the script actor.
extern i32 g_rolledMacca;
extern i32 g_rolledMagnetite;

// The unit OpPrintNumber appends to a printed value ("マッカ" or "ＭＡＧ"
// after the script read a macca or magnetite amount).
// @identity-TODO: its owner TU is unclaimed.
extern char g_numberUnit[64];

// The operand kinds ReadScriptOperand reads (and OpSetObjectField writes),
// named after the value each returns: literals, a long variable, item prices, macca and magnetite, and an
// object's stats (kind - OBJECT_STAT_0 indexes them), pools, alignment,
// equipment, training points and affiliations, and the last action's results.
GZ_ENUM_BEGIN(ScriptOperandKind)
    SCRIPT_OPERAND_BYTE = 0,
    SCRIPT_OPERAND_WORD = 1,
    SCRIPT_OPERAND_LONG = 2,
    SCRIPT_OPERAND_LONG_VAR = 3,
    SCRIPT_OPERAND_SIGNED_BYTE = 4,
    SCRIPT_OPERAND_SIGNED_WORD = 5,
    SCRIPT_OPERAND_ITEM_PRICE = 6,
    SCRIPT_OPERAND_ITEM_SELL_PRICE = 7,
    SCRIPT_OPERAND_ROLLED_MACCA = 9,
    SCRIPT_OPERAND_OBJECT_MACCA = 10,
    SCRIPT_OPERAND_ROLLED_MAGNETITE = 11,
    SCRIPT_OPERAND_OBJECT_MAGNETITE = 12,
    SCRIPT_OPERAND_WORD_ALIAS_1 = 13,
    SCRIPT_OPERAND_WORD_ALIAS_2 = 14,
    SCRIPT_OPERAND_WORD_ALIAS_3 = 15,
    SCRIPT_OPERAND_WORD_ALIAS_4 = 16,
    SCRIPT_OPERAND_WORD_ALIAS_5 = 17,
    SCRIPT_OPERAND_WORD_ALIAS_6 = 18,
    SCRIPT_OPERAND_WORD_ALIAS_7 = 19,
    SCRIPT_OPERAND_WORD_ALIAS_8 = 20,
    SCRIPT_OPERAND_WORD_ALIAS_9 = 21,
    SCRIPT_OPERAND_WORD_ALIAS_10 = 22,
    SCRIPT_OPERAND_WORD_ALIAS_11 = 23,
    SCRIPT_OPERAND_WORD_ALIAS_12 = 24,
    SCRIPT_OPERAND_OBJECT_STAT_0 = 25,
    SCRIPT_OPERAND_OBJECT_STAT_1 = 26,
    SCRIPT_OPERAND_OBJECT_STAT_2 = 27,
    SCRIPT_OPERAND_OBJECT_STAT_3 = 28,
    SCRIPT_OPERAND_OBJECT_STAT_4 = 29,
    SCRIPT_OPERAND_OBJECT_STAT_5 = 30,
    SCRIPT_OPERAND_OBJECT_STAT_6 = 31,
    SCRIPT_OPERAND_OBJECT_STAT_7 = 32,
    SCRIPT_OPERAND_OBJECT_STAT_8 = 33,
    SCRIPT_OPERAND_OBJECT_STAT_9 = 34,
    SCRIPT_OPERAND_OBJECT_STAT_10 = 35,
    SCRIPT_OPERAND_OBJECT_LEVEL = 36,
    SCRIPT_OPERAND_OBJECT_LEVEL_GAP = 37,
    SCRIPT_OPERAND_OBJECT_FAMILIARITY = 38,
    SCRIPT_OPERAND_OBJECT_FAMILIARITY_COUNT = 39,
    SCRIPT_OPERAND_ROLLED_MACCA_WITH_UNIT = 40,
    SCRIPT_OPERAND_ROLLED_MAGNETITE_WITH_UNIT = 41,
    SCRIPT_OPERAND_IGNORED_WORD = 42,
    SCRIPT_OPERAND_OBJECT_HP = 43,
    SCRIPT_OPERAND_OBJECT_MP = 44,
    SCRIPT_OPERAND_OBJECT_MAX_HP = 45,
    SCRIPT_OPERAND_OBJECT_MAX_MP = 46,
    SCRIPT_OPERAND_OBJECT_ALIGNMENT_B = 47,
    SCRIPT_OPERAND_OBJECT_ALIGNMENT_A = 48,
    SCRIPT_OPERAND_STATUS_CONDITION = 49,
    SCRIPT_OPERAND_OBJECT_ID = 56,
    SCRIPT_OPERAND_OBJECT_WEAPON_DEFENSE = 57,
    SCRIPT_OPERAND_OBJECT_FOURTH_GROUP_BASE = 58,
    SCRIPT_OPERAND_OBJECT_WEAPON = 59,
    SCRIPT_OPERAND_OBJECT_GUN = 60,
    SCRIPT_OPERAND_OBJECT_AMMO = 61,
    SCRIPT_OPERAND_OBJECT_RACE = 62,
    SCRIPT_OPERAND_OBJECT_WEAPON_GROUP_BASE = 63,
    SCRIPT_OPERAND_OBJECT_GUN_GROUP_BASE = 64,
    SCRIPT_OPERAND_OBJECT_MAGIC_GROUP_BASE = 65,
    SCRIPT_OPERAND_OBJECT_HEAD = 66,
    SCRIPT_OPERAND_OBJECT_BODY = 67,
    SCRIPT_OPERAND_OBJECT_ARMS = 68,
    SCRIPT_OPERAND_OBJECT_LEGS = 69,
    SCRIPT_OPERAND_OBJECT_ACCESSORY = 70,
    SCRIPT_OPERAND_OBJECT_TRAINING_0 = 71,
    SCRIPT_OPERAND_OBJECT_TRAINING_1 = 72,
    SCRIPT_OPERAND_OBJECT_TRAINING_2 = 73,
    SCRIPT_OPERAND_OBJECT_TRAINING_3 = 74,
    SCRIPT_OPERAND_ACTION_VALUE = 75,
    SCRIPT_OPERAND_HP_CHANGE = 76,
    SCRIPT_OPERAND_MP_CHANGE = 77,
    SCRIPT_OPERAND_EFFECT_CONDITION = 78,
    SCRIPT_OPERAND_BATTLE_RESULT_VALUE = 79,
    SCRIPT_OPERAND_OBJECT_EXPERIENCE = 80,
    SCRIPT_OPERAND_OBJECT_LEVEL_BONUS = 81,
    SCRIPT_OPERAND_OBJECT_AFFILIATION_0 = 82,
    SCRIPT_OPERAND_OBJECT_AFFILIATION_1 = 83,
    SCRIPT_OPERAND_OBJECT_AFFILIATION_2 = 84,
    SCRIPT_OPERAND_OBJECT_TITLE = 85,
    SCRIPT_OPERAND_OBJECT_WEAPON_VALUE = 86,
    SCRIPT_OPERAND_OBJECT_GUN_VALUE = 87,
    SCRIPT_OPERAND_OBJECT_AMMO_VALUE = 88,
    SCRIPT_OPERAND_OBJECT_HEAD_VALUE = 89,
    SCRIPT_OPERAND_OBJECT_BODY_VALUE = 90,
    SCRIPT_OPERAND_OBJECT_ARMS_VALUE = 91,
    SCRIPT_OPERAND_OBJECT_LEGS_VALUE = 92,
    SCRIPT_OPERAND_OBJECT_ACCESSORY_VALUE = 93
GZ_ENUM_END(ScriptOperandKind)

// Reads one typed operand from the script and returns its value's slot.
i32* ReadScriptOperand(void);

// What a stat contest compares beyond the CharacterStat stats (0..10) of the
// actor and the target: their levels, or the actor's level gap, familiarity
// or familiarity count.
GZ_ENUM_BEGIN(ContestStat)
    CONTEST_LEVEL = 11,
    CONTEST_LEVEL_GAP = 12,
    CONTEST_FAMILIARITY = 13,
    CONTEST_FAMILIARITY_COUNT = 14
GZ_ENUM_END(ContestStat)

void ReadContestValues(GZ_ENUM_PARAM(ContestStat, i16) stat, i32* own, i32* other, i16 swap);

// Macca, magnetite, twice the experience per able member, or first drop.
i32 GetBattleResultValue(i16 which);

// The last action's result, HP change, MP change, or experience drain.
i32 GetActionValue(i16 which);

#endif // GITEN_SCRIPT_SCRIPTOPERAND_H
