#ifndef GITEN_GAME_AUTOMAPMARK_H
#define GITEN_GAME_AUTOMAPMARK_H

#include <EnumDomain.h>
#include <Ints.h>

// @identity-TODO: the other automap image indices remain unnamed.
GZ_ENUM_BEGIN_SPLIT(AutomapMark, u8)
    MAP_MARK_PARTY_UP = 0,
    MAP_MARK_PARTY_RIGHT = 1,
    MAP_MARK_PARTY_DOWN = 2,
    MAP_MARK_PARTY_LEFT = 3,
    MAP_MARK_NPC = 4,
    MAP_MARK_OBJECT = 5,
    MAP_MARK_SERVICE_TERMINAL = 6,
    MAP_MARK_EXIT = 7,
    MAP_MARK_STAIRS_UP = 8,
    MAP_MARK_STAIRS_DOWN = 9,
    MAP_MARK_ELEVATOR = 10,
    MAP_MARK_NPC_RECORD = 11,
    MAP_MARK_ELECTRIC = 12,
    MAP_MARK_WEAPONS = 13,
    MAP_MARK_TRANSFER = 14,
    MAP_MARK_MEDICINE = 15,
    MAP_MARK_HERETIC = 16,
    MAP_MARK_HOSPITAL = 17,
    MAP_MARK_SPRING = 18,
    MAP_MARK_RECOVERY = 19,
    MAP_MARK_DEFENSE = 20,
    MAP_MARK_BAR = 21,
    MAP_MARK_DOJO = 22,
    MAP_MARK_ARM_TERMINAL = 23,
    MAP_MARK_BLANK = 24
GZ_ENUM_END_SPLIT(AutomapMark)

#endif // GITEN_GAME_AUTOMAPMARK_H
