#ifndef GITEN_GAME_CHARACTERSTAT_H
#define GITEN_GAME_CHARACTERSTAT_H

#include <Enums.h>

GZ_ENUM_BEGIN(CharacterStat)
    STAT_INTUITION = 0,
    STAT_MENTAL_STRENGTH = 1,
    STAT_MAGIC = 2,
    STAT_INTELLIGENCE = 3,
    STAT_PROTECTION = 4,
    STAT_STRENGTH = 5,
    STAT_VITALITY = 6,
    STAT_AGILITY = 7,
    STAT_DEXTERITY = 8,
    STAT_CHARM = 9,
    STAT_FORTUNE = 10,
    STAT_COUNT = 11
GZ_ENUM_END(CharacterStat)

#endif // GITEN_GAME_CHARACTERSTAT_H
