#ifndef GITEN_GAME_CONDITIONID_H
#define GITEN_GAME_CONDITIONID_H

#include <Enums.h>

// The status conditions, named after the game's condition-name strings
// (s_conditionNames); condition lists end with CONDITION_LIST_END.
// clang-format off
GZ_ENUM_BEGIN(ConditionId)
    CONDITION_ASH = 0,
    CONDITION_DEAD = 1,
    CONDITION_DYING = 2,
    CONDITION_COLLAPSE = 3,
    CONDITION_STONE = 4,
    CONDITION_PARALYSIS = 5,
    CONDITION_FREEZE = 6,
    CONDITION_POSSESSION = 7,
    CONDITION_ZOMBIE = 8,
    CONDITION_CURSE = 9,
    CONDITION_STUN = 10,
    CONDITION_SUFFOCATION = 11,
    CONDITION_BIND = 12,
    CONDITION_SLEEP = 13,
    CONDITION_PANIC = 14,
    CONDITION_POISON = 15,
    CONDITION_HALLUCINATION = 16,
    CONDITION_CHARM = 17,
    CONDITION_CONFUSION = 18,
    CONDITION_DANCE = 19,
    CONDITION_SHOCK = 20,
    CONDITION_ICE = 21,
    CONDITION_BURN = 22,
    CONDITION_BLIND = 23,
    CONDITION_MAGIC_SEAL = 24,
    CONDITION_DOZE = 25,
    CONDITION_BERSERK = 26,
    CONDITION_HIGH = 27,
    CONDITION_HAPPY = 28,
    CONDITION_TIPSY = 29,
    CONDITION_DRUNK = 30,
    CONDITION_SLIME = 31,
    CONDITION_SEVERE_POISON = 32,
    CONDITION_VAMPIRE = 33,
    CONDITION_INJURY = 34,
    CONDITION_COUNT = 35,
    CONDITION_LIST_END = -1,
    CONDITION_NONE = -1
GZ_ENUM_END(ConditionId);
// clang-format on

#endif // GITEN_GAME_CONDITIONID_H
