#ifndef GITEN_GAME_GAMESTATEID_H
#define GITEN_GAME_GAMESTATEID_H

#include <Enums.h>

// The game states DispatchGameState runs, named after each state's handler.
// @identity-TODO: states 2, 3, 4, 17 and 20 have no handler in the dispatcher.
GZ_ENUM_BEGIN_SPLIT(GameStateId, i16)
    GAME_STATE_RETURN = 0,
    GAME_STATE_WAIT = 1,
    GAME_STATE_SCRIPT_SCENE = 5,
    GAME_STATE_SCRIPT_CHOICE = 6,
    GAME_STATE_DISMISS_MENU = 7,
    GAME_STATE_TEXT_WINDOW = 8,
    GAME_STATE_SHOT = 9,
    GAME_STATE_ACTOR_SCENE = 10,
    GAME_STATE_FIELD_ENCOUNTER = 11,
    GAME_STATE_CLOSING_EFFECT = 12,
    GAME_STATE_SCREEN_FADE = 13,
    GAME_STATE_ITEM_USE = 14,
    GAME_STATE_SYSTEM_MENU = 15,
    GAME_STATE_FIELD_EXPLORATION = 16,
    GAME_STATE_CELL_SCENE = 18,
    GAME_STATE_ITEM_BUY_MENU = 19,
    GAME_STATE_FIELD_TEXT_SCENE = 21,
    GAME_STATE_WORLD_MAP = 22,
    GAME_STATE_BACKGROUND_SCENE = 23,
    GAME_STATE_BATTLE_ACTION = 24,
    GAME_STATE_STATUS = 25,
    GAME_STATE_FIELD_SKILL_USE = 26,
    GAME_STATE_LEVEL_UP = 27,
    GAME_STATE_ITEM_SELL_MENU = 28,
    GAME_STATE_FROZEN_FIELD_SCENE = 29,
    GAME_STATE_DDS_MENU = 30,
    GAME_STATE_FUSION_MENU = 31,
    GAME_STATE_AUTOMAP = 32,
    GAME_STATE_MESSAGE_BOX = 33,
    GAME_STATE_FIELD = 34,
    GAME_STATE_MESSAGE_SCENE_END = 35,
    GAME_STATE_PARTY_REORDER = 36,
    GAME_STATE_SCRIPT_ANIMATION = 37,
    GAME_STATE_GEM_ITEM_GIFT = 38,
    GAME_STATE_PICTURE_TRANSITION = 39,
    GAME_STATE_REPLACE_ROSTER_MEMBER = 40
GZ_ENUM_END_SPLIT(GameStateId)

#endif // GITEN_GAME_GAMESTATEID_H
