#ifndef GITEN_GAME_SCENEHOTSPOTKIND_H
#define GITEN_GAME_SCENEHOTSPOTKIND_H

#include <Enums.h>

GZ_ENUM_BEGIN(SceneHotspotKind)
    SCENE_HOTSPOT_OBJECT = 2,
    SCENE_HOTSPOT_BOX = 3
GZ_ENUM_END(SceneHotspotKind)

#endif // GITEN_GAME_SCENEHOTSPOTKIND_H
