#ifndef GITEN_GAME_SKILLFAMILY_H
#define GITEN_GAME_SKILLFAMILY_H

#include <EnumDomain.h>
#include <Ints.h>

// clang-format off
GZ_ENUM_BEGIN_SPLIT(SkillFamily, u8)
    SKILL_FAMILY_AGI = 1,
    SKILL_FAMILY_ZAN = 2,
    SKILL_FAMILY_DAWM = 3,
    SKILL_FAMILY_ZIO = 4,
    SKILL_FAMILY_BUFU = 5,
    SKILL_FAMILY_EXPEL = 6,
    SKILL_FAMILY_MEGI = 7,
    SKILL_FAMILY_REMEDY_REVIVE = 8,
    SKILL_FAMILY_MENTAL_ATTACK = 9,
    SKILL_FAMILY_SHIBABU = 11,
    SKILL_FAMILY_KAJA_KUNDA = 14,
    SKILL_FAMILY_DIA = 16,
    SKILL_FAMILY_FIRE_ATTACK = 22,
    SKILL_FAMILY_ICE_BREATH = 23,
    SKILL_FAMILY_AILMENT_ATTACK = 25,
    SKILL_FAMILY_SONG = 27,
    SKILL_FAMILY_SWORD_TECHNIQUE = 29,
    SKILL_FAMILY_MARTIAL_ART = 30,
    SKILL_FAMILY_ARROW = 33
GZ_ENUM_END_SPLIT(SkillFamily)
// clang-format on

#endif // GITEN_GAME_SKILLFAMILY_H
