#ifndef GITEN_FILE_DATATABLEID_H
#define GITEN_FILE_DATATABLEID_H

#include <EnumDomain.h>

// The id of a table file OpenDataFile reads, named from the reader that loads it.
GZ_ENUM_BEGIN_SPLIT(DataTableId, i16)
    DATA_TABLE_DEMONS = 0x0,
    DATA_TABLE_ITEM_RECORDS = 0x1,
    DATA_TABLE_MAP_MASK = 0x2,
    DATA_TABLE_MOON = 0x3,
    DATA_TABLE_SKILLS = 0x4,
    DATA_TABLE_FIELD_ENCOUNTER_WEIGHTS = 0x5,
    DATA_TABLE_EQUIPMENT_RULES = 0x6,
    DATA_TABLE_OBJECT_SCRIPT_SETS = 0x7,
    DATA_TABLE_ITEM_MENU_STOCK = 0x8,
    DATA_TABLE_FIELD_EVENTS = 0xa,
    DATA_TABLE_FUSION_RACES = 0xc,
    DATA_TABLE_WORLD_PLACES = 0xd,
    DATA_TABLE_FUSION_CLASSES = 0xf,
    DATA_TABLE_FUSION_RESTRICTIONS = 0x11,
    DATA_TABLE_GUN_DISTRIBUTION = 0x12,
    DATA_TABLE_MOON_FLAGS = 0x19,
    DATA_TABLE_WORLD_EVENTS = 0x20,
    DATA_TABLE_WORLD_ENCOUNTERS = 0x21,
    DATA_TABLE_AREA_SKILL_FLAGS = 0x28,
    DATA_TABLE_LEARNABLE_SKILLS = 0x30,
    DATA_TABLE_SKILL_LEARNING_REQUIREMENTS = 0x31,
    DATA_TABLE_ITEM_INDEX = 0x100,
    DATA_TABLE_FIELD_MESSAGES = 0x101,
    DATA_TABLE_WORLD_ENCOUNTER_BLOCKS_BEGIN = 0x1000,
    DATA_TABLE_WORLD_FIELD_INDEX = 0x10ff
GZ_ENUM_END_SPLIT(DataTableId)

#endif // GITEN_FILE_DATATABLEID_H
