#ifndef GITEN_MATH_FIELDSUBCELL_H
#define GITEN_MATH_FIELDSUBCELL_H

#include <EnumDomain.h>

// The row-major 3x3 floor position within a map cell.
GZ_ENUM_BEGIN_SPLIT(FieldSubcell, i16)
    FIELD_SUBCELL_ROW0_COL0 = 0,
    FIELD_SUBCELL_ROW0_COL1 = 1,
    FIELD_SUBCELL_ROW0_COL2 = 2,
    FIELD_SUBCELL_ROW1_COL0 = 3,
    FIELD_SUBCELL_CENTER = 4,
    FIELD_SUBCELL_ROW1_COL2 = 5,
    FIELD_SUBCELL_ROW2_COL0 = 6,
    FIELD_SUBCELL_ROW2_COL1 = 7,
    FIELD_SUBCELL_ROW2_COL2 = 8
GZ_ENUM_END_SPLIT(FieldSubcell)

#endif // GITEN_MATH_FIELDSUBCELL_H
